### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by zErtr** [zErtr/JuniorApi#1]
# Ideashop Api'ye erişim
- [ ] Php ile sürekli olarak token alma
- [ ] Php ile GET, POST, PUT, DELETE request denemelerinin yapılması 

# Google Image Search Api'ye (GISA) erişim
- [ ] GISA kullanımı (Araştırma)
- [ ] GISA ile GET request denemelerinin yapılması

# Ön hazırlık
- [ ] Ideashop projesindeki products endpointine deneme amaçlı isImageExist filtresinin eklenmesi

# Move Move Move !!!
- [ ] Resmi bulunmayan en az bir ürünün "product_id: 'product_name'" mantığı ile bir JSON dosyasına yazılması.
- [ ] Bir önceki maddenin tek seferde resmi bulunmayan bütün ürünlerde uygulanabilecek hale getirilmesi
- [ ] GISA'ya yazılan JSON dosyasındaki bir ürün_adı ile GET requesti atılması
- [ ] Bir önceki maddenin bütün JSON dosyası için uygulanabilecek hale getirilmesi
- [ ] Bulunan bir resmin products endpointi ile ilgili ürünle eşleştirilmesi
- [ ] Bir önceki maddenin tüm ürünleri güncelleyebilecek hale getirilmesi
- [ ] Güncelleme sonunda kaç ürün güncellendi kaçı resimsiz kaldı bunun "gucelleme_raporu.txt" dosyasına yazılması
